# Generated by Django 5.1.1 on 2024-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_shelter_animal_adopted_by_alter_animal_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'Хлопчик'), ('female', 'Дівчинка')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animal_photos/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кіт'), ('other', 'Інше')], default='other', max_length=10),
        ),
    ]
